llm:
  mode: sagemaker

sagemaker:
  llm_endpoint_name: ${SAGEMAKER_LLM_ENDPOINT_NAME:huggingface-pytorch-tgi-inference-2023-09-25-19-53-32-140}
  embedding_endpoint_name: ${SAGEMAKER_EMBEDDING_ENDPOINT_NAME:huggingface-pytorch-inference-2023-11-03-07-41-36-479}